flashkard/models.py
#PROGRAMMER: PARAM CHORDIYA
#ROLL NO: 21f1003953
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(30), unique=True, nullable = False)
    password = db.Column(db.String(300), nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    score = db.Column(db.Integer, default = 0)
    udeck = db.relationship('Deck', cascade='all, delete-orphan', backref='deck')

class Deck(db.Model):
    __tablename__ = 'deck'
    id = db.Column(db.Integer, primary_key=True)
    deck_name = db.Column(db.String(30))
    user = db.Column(db.String, db.ForeignKey('user.username'), nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    score = db.Column(db.Integer, default=0)
    is_public = db.Column(db.Boolean, default = False)
    last_rev = db.Column(db.DateTime(timezone=True), default=func.now())
    dcard = db.relationship('Card', cascade='all, delete-orphan', backref='card')

class Card(db.Model):
    __tablename__ = 'card'
    card_id = db.Column(db.Integer, primary_key=True)
    front = db.Column(db.String(512), nullable = False)
    back = db.Column(db.String(512), nullable = False)
    score = db.Column(db.Integer, default = 0)
    deck = db.Column(db.String, db.ForeignKey('deck.deck_name'), nullable = False)

flashkard/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager, login_manager
from flask_restful import Api


db = SQLAlchemy()
DB_NAME = "project.sqlite3"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'param'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    api = Api(app)
    from .api import UserAPI, DeckAPI, CardAPI
    api.add_resource(UserAPI, '/api/user', '/api/user/<string:username>')
    api.add_resource(DeckAPI, '/api/deck/<string:username>')
    api.add_resource(CardAPI, '/api/<string:username>/<string:deck>/card', '/api/card/<string:card_id>','/api/<string:deck>')
    from .views import views
    app.register_blueprint(views, url_prefix="/")
    from .models import User, Deck, Card
    create_db(app)
    login_manager = LoginManager()
    login_manager.login_view = "views.login"
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


    return  app, api

def create_db(app):
    if not path.exists("flashkard/"+ DB_NAME):
        db.create_all(app=app)
    print('DATABASE ALREADY EXISTS')

flashkard/views.py
#PROGRAMMER: PARAM CHORDIYA
#ROLL NO: 21f1003953
from re import S
from flask import Blueprint, render_template, request, flash
from flask_login import login_user, logout_user, current_user
from flask_login.utils import login_required
from werkzeug.utils import redirect
from .models import User, Deck, Card
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
import requests
from datetime import datetime

views = Blueprint("views", __name__)

BASE = 'http://127.0.0.1:5000'

@views.route('/dashboard', methods = ['GET', 'POST'])
@login_required
def home():
    data = requests.get(BASE+f'/api/deck/{current_user.username}')
    
    return render_template('dashboard.html', decks=data.json(), user=current_user.username)

@views.route('/', methods=['GET'])
def landing():
    return render_template('landing.html')


@views.route('/review/<string:deck>', methods = ['GET', 'POST'])
@login_required
def review(deck):
    t = datetime.now()
    d=Deck.query.filter_by(deck_name=deck).first()
    d.last_rev=t
    db.session.commit()
    data=requests.get(BASE+ f'/api/{current_user.username}/{deck}/card')
    

    if data:
        return render_template('review.html', front = data.json()['front'], back = data.json()['back'], deck=data.json()['deck'], card_id=data.json()['card_id'])
    else:
        return render_template('review.html', deck=deck, data=True)

@views.route('/review/<string:deck>/<int:card_id>', methods = ['GET', 'POST'])
def score(deck,card_id):
    if request.method == 'POST':
        c = Card.query.filter_by(card_id=card_id).first()
        s = int(request.form.get('score'))
        c.score = s
        db.session.commit()
        d= Deck.query.filter_by(deck_name=deck, user=current_user.username).first()
        cn = Card.query.filter_by(deck=deck).count()
        d.score = d.score + (c.score/cn)
        db.session.commit()
        return redirect(f'/review/{deck}')




@views.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get("username")
        password = request.form.get("password")

        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect('/dashboard')
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('Username does not exist.', category='error')

    return render_template('login.html')




@views.route('/register', methods = ['GET', 'POST'])
def register():
    return render_template('register.html')


@views.route('/<string:deck>/addcard', methods=['GET', 'POST'])
def addcard(deck):
    return render_template('addcard.html')


@views.route('/<string:user>/deck/<string:deck>/delete', methods=['GET','POST'])
def deletedeck(deck, user):
    d= Deck.query.filter_by(deck_name=deck, user=user).first()
    db.session.delete(d)
    db.session.commit()
    return redirect('/dashboard')



@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect('/')

flashkard/templates/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
        
        <header class="p-3  text-white">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a style="color: black " href="/" class="d-flex align-items-center mb-2 mb-lg-0  text-decoration-none">
                FLASH CARDS
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/dashboard" class="nav-link px-2 text-secondary"> Home</a></li>
                
                </ul>

                

                <div class="text-end">
                <a href="{{ url_for('views.logout') }}" class="btn btn-outline-dark btn-warning me-2">Logout</a>
                <!--a href="{{ url_for('views.register') }}" class="btn btn-warning">Sign-up</a-->
                </div>
            </div>
            </div>
        </header>

        <div class="container mt-5 mb-5">
            <div class="row mt-1">
                {% for d in decks %}
                <div class="col-md-4">
                    <div class= "container">
                        <div class="card">
                            <div class="front">{{ d['deck_name'] }}</div>
                            <div class="back">
                                <ul>
                                    <p> <b>score:</b><br> {{ d['score'] }} </p>
                                    <p> <b>last review time:</b><br> {{ d['last_rev'] }} </p>
                                </ul>
                                <div class="btn" role="group">
                                    <a href="/review/{{ d['deck_name'] }}" class="btn btn-outline-dark">Add Cards/Review</a>
                                    <a href="/{{ user }}/deck/{{ d['deck_name'] }}/delete" class="btn btn-outline-dark">Delete Deck</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="col-md-4 text-end btn-w">
                    <!-- Button trigger modal -->
                    
                    <br><button type="button" class="btn btn-outline-dark add" data-toggle="modal" data-target="#exampleModal">
                        Add Deck
                    </button>
                    

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">ADD NEW DECK!</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <form class="row g-3" action="/api/deck/{{ user }}" method="POST">
                              <div class="col-auto">
                                <label for="deckname" class="visually-hidden">Deck Name</label>
                                <input type="text" class="form-control" id="inputPassword2" placeholder="Deck Name" name="deck_name">
                              </div>
                              <div class="col-auto">
                                <button type="submit" class="btn btn-primary mb-3">Add</button>
                              </div>
                            </form>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            
        </div>
        
    </body>
</html>

flashkard/templates/landing.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Flash Card  </title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/landing.css') }}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
        <style type="text/css">
            

        </style>
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div>
                <div class="header_main"><a style="color: red" class="navbar-brand" href="{{ url_for('views.landing') }}" al>FLASH CARDS</a></div>
                <!--button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button-->
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <button class="login"><span><a class="nav-link" href="{{ url_for('views.login') }}">Login</a></span></button>
                        <button class="login"><span><a class="nav-link" href="{{ url_for('views.register') }}">SignUp</a></span></button>
                    </ul>
                    
                </div>
            </div>
            
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <!--div class="container px-4 px-lg-5 h-100"-->
            <div>
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 >Let's Use Flash Cards to learn Better!</h1>
                        <p class="para">Get started to find out</p>
                        
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="para" class="text-white-75 mb-5">Start learning by creating your own personalized Flash Cards!</p>
                        <!--a class="para" class="btn btn-primary btn-xl" href="{{ url_for('views.register') }}">Get Started</a-->
                    </div>
                </div>
            </div>
        </header>
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>

flashkard/templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
   
        <style>
            body {
               background-color: #e9bcb7;
               background-image: linear-gradient(to right, #f78ca0 0%, #f9748f 19%, #fd868c 60%, #fe9a8b 100%);
               
            }
            .login-main-text{
               margin-top: 15px;
               text-align: center;
            }
            
         </style>


    </head>
    <body>
    <!--header class="p-3 bg-dark text-white"-->
      <header class="p-3">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FLASH CARDS
                </a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <a href="/dashboard" class="nav-link px-2 text-secondary">Home</a>
                </ul>


                

                <div class="text-end">
                <a href="{{ url_for('views.login') }}" class="btn btn-outline-dark btn-warning me-2">Login</a>
                <a href="{{ url_for('views.register') }}" class="btn btn-outline-dark btn-warning">Sign-up</a>
                </div>
            </div>
            </div>
        </header>
         
        <div class="sidenav">
         <div class="login-main-text">
            <h2>Welcome To The Login Page</h2><br>
            <h3>Why Use Flash Cards?</h3><br>
            <i><ul>
            <p>Flash cards are strategically designed to enhance and encourage active recall</p>
            <p>Practicing active recall creates stronger neural connections in the brain — making it a very effective method for improving memory</p><br>
            </ul>
         </div>
      </div>
      <div class = "container" align = "center">
      <div class="main">
         <div class="col-md-6 col-sm-12">
         {% with messages = get_flashed_messages(with_categories=True) %}
         {% if messages %}
         {% for category, message in messages %}
            <div class = "alert alert-danger alert-dismissable fade show" role = "alert">
            {{ message }} 
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
         {% endfor %}
         {% endif %}
         {% endwith %}
            <div class="login-form">
               <form action = "{{ url_for('views.login') }}" method = "POST">
                  <div class="form-group">
                     
                     <input type="text" class="form-control" placeholder="User Name" name="username">
                  </div>
                  <div class="form-group">
                     <br>
                     <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                  <br>
                  <i>Not a user yet?, <a href="{{ url_for('views.register') }}">Register now!</a></i><br>
                  
                  <button style="width:100px;margin: 15px;" type="submit" class="btn btn-dark">Login</button>
               </form>
            </div>
         </div>
      </div>
      </div>
    
        
        <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

flashkard/templates/register.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
        <style> 
        body {
            background-color: #e9bcb7;
            background-image: linear-gradient(to right, #f78ca0 0%, #f9748f 19%, #fd868c 60%, #fe9a8b 100%);
        }
        
        </style>


    </head>
    <body>  
     <header class="p-3  text-white">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FLASH CARDS
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
                </ul>

                
                <div class="text-end">
                <a href="{{ url_for('views.login') }}" class="btn btn-outline-dark btn-warning me-2">Login</a>
                <a href="{{ url_for('views.register') }}" class="btn btn-outline-dark btn-warning">Sign-up</a>
                </div>
            </div>
            </div>
        </header>
   
      <div class="sidenav">
         <div class="login-main-text">
            <h2>SIGN UP & ENJOY!</h2><br>
            <h3>Why Use Flash Cards?</h3><br>
            <i><ul>
            <p>Flash cards are strategically designed to enhance and encourage active recall</p>
            <p>Practicing active recall creates stronger neural connections in the brain — making it a very effective method for improving memory</p><br>
            </ul></i>
         </div>
      </div>
      
      <div class = "container" align = "center">
      <div class="main">
         <div class="col-md-6 col-sm-12">
         <div class="container">
            {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            {% for category, message in messages %}
               <div class = "alert alert-danger alert-dismissable fade show" role = "alert">
               {{ message }} 
               <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
               </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
         </div>
            <div class="login-form">
               <form action ="/api/user" method = "POST">
                  <div class="form-group">
                     
                     <input type="text" class="form-control" placeholder="User Name" name="username">
                  </div>
                  <div class="form-group">
                     <br>
                     <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                  <br>
                  
                  
                  <button style="width:100px;margin: 15px;" type="submit" class="btn btn-dark">Register</button>
                  <p>Have an account already?</p> 
                  <button class="lginbtn" href="{{ url_for('views.login') }}">Login now!</button></p>
               </form>
            </div>
         </div>
      </div>
      </div>
      
    
        
        <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

flashkard/templates/review.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/review.css') }}">
    </head>
    <body>
        <header class="p-3  text-white">
            <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FLASH CARDS
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{{ url_for('views.home') }}" class="nav-link px-2 text-secondary">Home</a></li>
                
                </ul>
                <div class="text-end">
                <a href="{{ url_for('views.logout') }}" class="btn btn-outline-dark btn-warning me-2">Logout</a>
                
                </div>
            </div>
            </div>
        </header>

<br><br>
    <center>
        <!-- Button trigger modal -->
        <button style="margin-bottom: 50px;"type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#exampleModal">
          + Add Cards
        </button>
        <br>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">ADD CARD!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form class="row g-3" action="/api/{{ deck }}" method="POST">
                              <div class="col-auto">
                                <label for="front" class="visually-hidden">Front</label>
                                <input type="text" class="form-control" id="front" placeholder="front..." name="front">
                                <br>
                                <label for="back" class="visually-hidden">Back</label>
                                <input type="text" class="form-control" id="back" placeholder="back..." name="back">
                              </div>
                              <div class="col-auto">

                                <br>
                                <br>
                                <button type="submit" class="btn btn-primary mb-3">Add</button>
                                
                              </div>
                            </form>
              </div>
              <div class="modal-footer">
                
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                
              </div>
            </div>
          </div>
        </div>
    </center>

        <center>
            <div class="big">
              
            <!--div class="cardcontainer">
                <div class="card">
                  
                    <div class="front"> Front: {% if data %} No Cards Yet {% else %} {{front}} {% endif %}</div>
                    
                    <div  class="back"> Back: {% if data %} Click Add Cards to get started {% else %} {{back}} {% endif %}</div>
                </div> 
            </div-->
            
            <div class="flip-card">
              <div class="flip-card-inner">
                <div class="flip-card-front">
                  <div class="front"> <p>Front:</p> {% if data %} No Cards Yet {% else %} {{front}} {% endif %}</div>
                </div>
                <div class="flip-card-back">
                  <div  class="back"> <p>Back:</p> {% if data %} Click Add Cards to get started {% else %} {{back}} {% endif %}</div>
                </div>
              </div>
            </div>
 

            <form id="autoform" action="/review/{{ deck }}/{{ card_id }}" method="POST" name="autoform">    
                <div class="rating">
                  <br>
                  <p class="rate">Please rate below depending on how easy or difficult was it for you to answer the displayed question and the card will automatically be shuffled!</p>
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata4" value="10" {% if data %} disabled {% endif %}><label for="rata4">Easy</label><br>
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata3" value="8" {% if data %} disabled {% endif %}><label for="rata3">Average</label><br>
                    <input onclick="document.getElementById('autoform').submit();" type="radio" name="score" id="rata2" value="6" {% if data %} disabled {% endif %}><label for="rata2">Hard</label>
                    

                </div>
            </form>

            </div>   
        </center>


        
        
    </body>
</html>